export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILED="LOGIN_FAILED"

export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILED="REGISTER_FAILED"

// export const ADD_ACTIVITY="ADD_ACTIVITY"
// export const GET_ACTIVITY="GET_ACTIVITY"


// export const UPDATE_ACTIVITY="UPDATE_ACTIVITY"
// export const DELETE_ACTIVITY="DELETE_ACTIVITY"
